### ISSUE TITLE
redisKey undefined in S3Plugin.js

### ISSUE THREAD

**Issue by olioooo** [kuzzleio/kuzzle-plugin-s3#17]
## Current Behavior

In the File S3Plugin.js line 195:
![Screenshot from 2020-10-07 11-56-20](https://user-images.githubusercontent.com/65018077/95316896-b46a9d00-0894-11eb-8d14-622b5631f781.png)
## Possible Solution

I think it needs to be:
    const fileKey = this._stringArg(request,fileKey);
    const redisKey = `${this.config.redisPrefix}/${fileKey}`;

**Comment by Aschen** [comment]
Hi,

You code will crash because you are using `filekey` before initialization.

The following code try to get an string argument named `fileKey` from the request `this._stringArg(request, 'fileKey')`
If you don't send a `fileKey` argument, then it's undefined and you have an error

**Comment by olioooo** [comment]
Hey sorry i forgot the checkmarks at 'fileKey' but what i meant was the redisKey needs to be const,
const fileKey = this._stringArg(request, 'fileKey');
const redisKey = `${this.config.redisPrefix}/${fileKey}`;

**Comment by Aschen** [comment]
`redisKey` is also `const` since it's on the same declaration line as `fileKey` (notice the comma `,`).

But I agree this syntax is not part of our coding standard anymore so if you want to correct this with a PR it's welcomed :smile:

**Comment by olioooo** [comment]
Thank you i didn't know this syntax
PR is done
