### ISSUE TITLE
Allow plugin to use minio S3 backend 

### ISSUE THREAD

**Issue by gpulido** [kuzzleio/kuzzle-plugin-s3#6]
[Minio S3](https://min.io) is a S3 api compatible sustitute for amazon S3 that allows to deploy selfhosting. It would be nice to allow the s3 plugin to provide as a configuration option a minio endpoint (instead of having hardcoded the amazon url) so it can be used on a docker stack with kuzzle that also include minio as self hosting media db.
Theoretically the only change needed is the basic url as minio has exactly the same api than amazon s3.

### Update
The configuration steps needed on the minion part are pretty straightforwards.
The bucket policy is exactly the same than on the amazon s3, so it is just needed to go to the bucket config folder **.minio.sys/config/{your-bucket-name}/policy.json** and add the statement 
``` Json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AddPerm",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::your-bucket-name/*"
    }
  ]
}
```
Minio doesn't need to enable CORS as it is already enabled.
So the only thing that would be needed on the plugin is to expose the base url and not just the region as a parameter.

**UPDATE2**
The plugin is using the official aws-sdk implementation. This is the guide to use the same library to access to minio:
[minio with aws-sdk](https://docs.min.io/docs/how-to-use-aws-sdk-for-javascript-with-minio-server.html)

**Comment by Aschen** [comment]
Hi @gpulido,

Glad to see that Kuzzle and this plugin fit your needs!
We will try to consider this enhancement of the s3 plugin but since we don't have much time, feel free to propose a pull request making these changes :-)
I will be pleased to assist you in the process.

Cheers,

**Comment by gpulido** [comment]
Hello!
Thank you for the amazing project.
I think that to be able to add the selfhosting minio to the "selfhosted kuzzle" stack could be a good step towards being a "FOOS firebase- selfhosting" alternative.

Regarding the plugin, I have two questions:
1) The creation of the presigned url and uploading of file is being done using the aws-sdk getSignedUrl  and putobject methods. Why the equivalent method getObject is not used to provide the "download" functionallity? It would allow to get ride of the building of the complete url build... and also could be used to avoid having to give access to the file to everyone that have the url, as a presigned url could be generated and then provide to give access to the file. (Maybe I'm wrong here...)

2) I think that the kuzzle documentation lacks a proper explanation of how to install / deploy a plugin onto an already running instance (in my case a docker swarm one...) It is not very clear what is needed, also the plugins folder is not mapped by default on the docker compose.
Cheers,

**Comment by Aschen** [comment]
Yes you are right, it could nice to allow user to get ride of private source software :-)
Maybe I will write an article if I have the time.

Concerning your questions:

1) Since an `uuid` is added to the url, users cannot guess where the file are stored. I designed this plugin mainly for image uploading so I didn't need to have more control on who is able to access the file or not but it could also be an enhancement yes.

2) We are aware that the documentation part about plugin can be difficult to understand for people who discover Kuzzle. Also because our way of dealing with plugin is not very common in the Node.js world. There is many items on the roadmap to simplify that:
 - include essentials plugins into the core
 - rewrite the plugin system to use NPM instead of directory on the filesystem
You can check out the public roadmap here: https://trello.com/b/za9vOgRh/kuzzle-public-roadmap

**Comment by gpulido** [comment]
Hello again,
I have already spent some time understanding kuzzle, plugin s3 and aws-js plugin, and the changes needed are minimun: just expose an optional argument "endpoint", make the region argument optional, and check that one of the two are filled.
If the region is filled use it to create an endpoint that is going to be used to build the baseurl on the plugin. And that will be all.
I will try to do the changes and a pr on the next couple of days.
Regarding the questions:
1) I come to that same conclusion, the id is not very common and hard to figure out, so I understand now why made it public.
2) At the end to reinvent the wheel is always problematic :)

I'm thinking if the plugin could go one step forward and just do the ask for url / validation / uploading the file and creating an entry on a kuzzle collection "images" (parametrizable)  with the id + url.
Then to retrieve the image from the collection the steps would be in reverse.
THis way the use of S3 is completely abstracted and wrapped by kuzzle, so the user only need to provide the S3 keys once and voila, kuzzle now have image storage.
Something very similar to the way elasticsearch is being abstracted...
Just thinking ahead :)

**Comment by Aschen** [comment]
Thanks you for that if you have the time to make a contribution! It's always appreciated :-)

About the step forward for the plugin, what you suggest is that the plugin should also save the image to an internal collection so users can just use the image ID in the rest of their application ?

**Comment by Aschen** [comment]
Merged https://github.com/kuzzleio/kuzzle-plugin-s3/pull/8
